### ISSUE TITLE
menu item: font weight und line-height

### ISSUE THREAD

**Issue by StefanEndress** [magicasaservice/mirror-tokens#26]
### Description of the bug

<img width="434" alt="image" src="https://github.com/magicasaservice/mirror-tokens/assets/5189598/2b29a12a-17b1-45a8-9830-70098ca08c3f">

### Steps To Reproduce

wrong styling

**Comment by robinscholz** [comment]
what exactly is wrong? font weight maybe? In that case that must be due to a wrong value in the token
